---
- name: Install Nginx.
  apt:
    name: nginx
    state: present

- name: Add webconfig
  template:
    src: pdns-admin.conf.j2
    dest: /etc/nginx/sites-available/pdns-admin.conf

- name: create symlink
  file:
    src: /etc/nginx/sites-available/pdns-admin.conf
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: restart_nginx
  service: 
    name: nginx
    enabled: yes
    state: restarted


