all:
  vars:
    mysql_database: pdns
    mysql_user: pdns_user
    mysql_user_password: 13

  hosts:
    ns1:
      ansible_host: 178.128.194.154
      mysql_role: master
      mysql_server_id: 1
      mysql_replication_master: 10.114.0.3
      mysql_replication_password: 13
   # ns2:
   #   ansible_host: 207.154.206.119
   #   mysql_role: slave
   #   mysql_server_id: 2
